project:
  type: website

website:
  title: "Basic Statistics Workshop"
  sidebar:
    style: "floating"
    search: true
    contents:
      - Intro.qmd
      - Jamovi.qmd
      - DescViz.qmd
      - Probability.qmd
      - StatsTestJamovi.qmd




format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

